### ISSUE TITLE
Incompatibilty with 4.15

### ISSUE THREAD

**Issue by Cypaubr** [gameDNAstudio/AndroidManifestConfigurator#1]
The extension seems being incompatible with the 4.15.0 version of UE.

**Comment by gameDNA-Helix** [comment]
What do you mean? Could you be more specific? What error occurs?

**Comment by Cypaubr** [comment]
The plugin does not appear in the plugins list. When I edited the plugin file to change the engine version in order to match mine, UE4 displays an error message like "In compatible plugin AndroidManifestConfigurator detected. Do you want to disable it?".

**Comment by gameDNA-Helix** [comment]
Do you have Launcher or GitHub version of the engine?
If Launcher, did you download precompiled version of plugin from "Releases" tab? https://github.com/gameDNAstudio/AndroidManifestConfigurator/releases

**Comment by Cypaubr** [comment]
This is the launcher version and yes I downloaded the last version of the plugin.

**Comment by gameDNA-Helix** [comment]
But precompiled version or directly from branch?

**Comment by Cypaubr** [comment]
The last release I mean

**Comment by gameDNA-Helix** [comment]
What operating system? Windows, macOS, Linux?

**Comment by Cypaubr** [comment]
Windows

**Comment by gameDNA-Helix** [comment]
I think we don't understand. It should work... Why did you change engine version in .uplugin? It is associated to 4.15 so from which version you changed it?

**Comment by Cypaubr** [comment]
With or without changing .uplugin, the plugin does not work.

**Comment by gameDNA-Helix** [comment]
@Cypaubr really sorry but I still don't understand :( 

1. You have UE 4.15
2. You have Launcher version
3. You have Windows 
4. You have the latest plugin version
5. I don't know what you modified in .uplugin because plugin is already for 4.15...
6. You didn't response me if you downloaded precompiled version or directly from branch so this is the last thing to explain. Precompiled versions you can find on "releases" tab: https://github.com/gameDNAstudio/AndroidManifestConfigurator/releases
